/*Create a table called "buildings" that has the following attributes to it:

name, the full name of the building, which is a string of 80 characters
shortname, a shortened reference to the building name, which is a string of 10 characters
id, an integer primary key that is auto-generated by the database (that is to say, you do not specify the id when you insert values into the table)
In addition, make sure the following constraints are enforced:

name can never be NULL
shortname must always be unique*/

CREATE TABLE buildings(
name TEXT(80) NOT NULL,
shortname TEXT(10),
id INTEGER,
PRIMARY KEY(id)
) ;

INSERT INTO buildings (name, shortname)
VALUES('Mary Gates Hall', 'MGH'),
('Kane Hall', 'KNE'),
('Raitt Hall', 'RAI');

SELECT * FROM buildings;

/*Buildings also have rooms, so create a second table, called "rooms" that has the following:

number, an integer identifier for the room
buildingid, an integer referring to the buildings primary key
seating, an integer reflecting the number of open seats in the room*/

CREATE TABLE rooms(
number INTEGER,
buildingid INTEGER,
seating INTEGER,
PRIMARY KEY(buildingid),
FOREIGN KEY(buildingid) REFERENCES buildings (id)
) ;

INSERT INTO rooms(number, seating)
VALUES(234, 150),
(183, 35),
(146, 100);


SELECT * FROM rooms;
